### ISSUE TITLE
support for google managed certs?

### ISSUE THREAD

**Issue by red8888** [DivvyCloud/k8s-helm-chart#3]
I think this would be pretty trivial to add to the helm chart since you already added ingress support

for example in the chart templates:
```
#managedCertificates.yaml
{{- range $key, $value := .Values.certificates }}
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: '{{ $value.certName }}'
  labels:
    app.kubernetes.io/name: {{ include "divvycloud.name" $ }}
    helm.sh/chart: {{ include "divvycloud.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}

spec:
  domains:
    - {{ $value.domainName }}
{{- end }}
```

In values.yaml:
```
certificates:
  atlantis:
    certName: 'my-google-managed-cert'
    domainName: 'my-domain.com'

ingress:
  annotations:
    networking.gke.io/managed-certificates: 'my-google-managed-cert'
    kubernetes.io/ingress.global-static-ip-name: 'my-reserved-ip'
   ....
```

You already added the ingress and with it support for gce reserved IPs might as well add managed certs too! :)
